export const seoKeywords = [
  'Auto glass repair Sydney',
  'Auto glass repair Melbourne',
  'Car window repair Sydney',
  ' Car window repair Melbourne',
  ' Mobile auto glass repair Sydney',
  ' Mobile auto glass repair Melbourne',
  ' Windscreen replacement Sydney',
  ' Windscreen replacement Melbourne',
  ' Car glass repair Sydney',
  ' Car glass repair Melbourne',
  ' Auto glass replacement Sydney',
  ' Auto glass replacement Melbourne',
  ' Mobile windscreen repair Sydney',
  ' Mobile windscreen repair Melbourne',
  ' Car side window replacement Sydney',
  ' Car side window replacement Melbourne',
  ' Rear window replacement Sydney',
  ' Rear window replacement Melbourne',
  ' Truck windscreen replacement Sydney',
  ' Truck windscreen replacement Melbourne',
  ' Emergency auto glass repair Sydney',
  ' Emergency auto glass repair Melbourne',
  ' Affordable windscreen replacement Sydney',
  ' Affordable windscreen replacement Melbourne',
  ' Auto glass repair cost Sydney',
  ' Auto glass repair cost Melbourne',
  ' Best auto glass repair Sydney',
  ' Best auto glass repair Melbourne',
  ' Cheap windshield repair Sydney',
  ' Cheap windshield repair Melbourne',
  ' Car mirror repair Sydney',
  ' Car mirror repair Melbourne',
  ' Vehicle glass repair Sydney',
  ' Vehicle glass repair Melbourne',
  ' Windshield scratch repair Sydney',
  ' Windshield scratch repair Melbourne',
  ' Car door window repair Sydney',
  ' Car door window repair Melbourne',
  ' Mobile auto glass replacement Sydney',
  ' Mobile auto glass replacement Melbourne',
  ' 24-hour mobile auto glass repair Sydney',
  ' 24-hour mobile auto glass repair Melbourne',
  ' Auto glass chip repair Sydney',
  ' Auto glass chip repair Melbourne',
  ' Vehicle window repair Sydney',
  ' Vehicle window repair Melbourne',
  ' Car glass shop Sydney',
  ' Car glass shop Melbourne',
  ' Auto glass companies Sydney',
  ' Auto glass companies Melbourne',
  ' Mobile power window repair Sydney',
  ' Mobile power window repair Melbourne',
  ' Cheap auto glass repair Sydney',
  ' Cheap auto glass repair Melbourne',
  ' Car windscreen repair Sydney',
  ' Car windscreen repair Melbourne',
  ' Automotive glass Sydney',
  ' Automotive glass Melbourne',
  ' Car window fix Sydney',
  ' Car window fix Melbourne',
  ' Windscreen chip repair Sydney',
  ' Windscreen chip repair Melbourne',
  ' Car window replacement Sydney',
  ' Car window replacement Melbourne',
  ' Auto glass crack repair Sydney',
  ' Auto glass crack repair Melbourne',
  ' Vehicle glass replacement Sydney',
  ' Vehicle glass replacement Melbourne',
  ' Mobile windscreen chip repair Sydney',
  ' Mobile windscreen chip repair Melbourne',
  ' Emergency windscreen replacement Sydney',
  ' Emergency windscreen replacement Melbourne',
  ' Affordable auto glass services Sydney',
  ' Affordable auto glass services Melbourne',
  ' Car window regulator repair Sydney',
  ' Car window regulator repair Melbourne',
  ' Rear windscreen replacement Sydney',
  ' Rear windscreen replacement Melbourne',
  ' Side window glass repair Sydney',
  ' Side window glass repair Melbourne',
  ' Front windscreen replacement Sydney',
  ' Front windscreen replacement Melbourne',
  ' Auto glass scratch removal Sydney',
  ' Auto glass scratch removal Melbourne',
  ' Car window tinting Sydney',
  ' Car window tinting Melbourne',
  ' Windscreen leak repair Sydney',
  ' Windscreen leak repair Melbourne',
  ' Auto glass replacement near me',
  ' Car window repair cost Sydney',
  ' Car window repair cost Melbourne',
  ' Mobile car glass repair Sydney',
  ' Mobile car glass repair Melbourne',
  ' Auto glass repair reviews Sydney',
  ' Auto glass repair reviews Melbourne',
  ' Windscreen repair specialists Sydney',
  ' Windscreen repair specialists Melbourne',
  ' Cheap windscreen repair Sydney',
  ' Cheap windscreen repair Melbourne',
  ' Auto glass repair and replacement Sydney',
  ' Auto glass repair and replacement Melbourne',
  ' Car window glass replacement Sydney',
  ' Car window glass replacement Melbourne',
  ' Mobile windscreen services Sydney',
  ' Mobile windscreen services Melbourne',
  ' Auto glass repair experts Sydney',
  ' Auto glass repair experts Melbourne',
  ' Windscreen replacement cost Sydney',
  ' Windscreen replacement cost Melbourne',
  ' Car glass repair cost Sydney',
  ' Car glass repair cost Melbourne',
  ' Auto glass repair quotes Sydney',
  ' Auto glass repair quotes Melbourne',
  ' Windscreen repair near me',
  ' Mobile windscreen replacement Sydney',
  ' Mobile windscreen replacement Melbourne',
  ' Auto glass repair deals Sydney',
  ' Auto glass repair deals Melbourne',
  ' Car window repair deals Sydney',
  ' Car window repair deals Melbourne',
  ' Windscreen repair deals Sydney',
  ' Windscreen repair deals Melbourne',
  ' Auto glass repair promotions Sydney',
  ' Auto glass repair promotions Melbourne',
  ' Car window repair promotions Sydney',
  ' Car window repair promotions Melbourne',
  ' Windscreen repair promotions Sydney',
  ' Windscreen repair promotions Melbourne',
  ' Auto glass repair discounts Sydney',
  ' Auto glass repair discounts Melbourne',
  ' Car window repair discounts Sydney',
  ' Car window repair discounts Melbourne',
  ' Windscreen repair discounts Sydney',
  ' Windscreen repair discounts Melbourne',
  ' Auto glass repair specials Sydney',
  ' Auto glass repair specials Melbourne',
  ' Car window repair specials Sydney',
  ' Car window repair specials Melbourne',
  ' Windscreen repair specials Sydney',
  ' Windscreen repair specials Melbourne',
  ' Auto glass repair packages Sydney',
  ' Auto glass repair packages Melbourne',
  ' Car window repair packages Sydney',
  ' Car window repair packages Melbourne',
  ' Windscreen repair packages Sydney',
  ' Windscreen repair packages Melbourne',
  ' Auto glass repair bundles Sydney',
  ' Auto glass repair bundles Melbourne',
  ' Car window repair bundles Sydney',
  ' Car window repair bundles Melbourne',
  ' Windscreen repair bundles Sydney',
  ' Windscreen repair bundles Melbourne',
  ' Auto glass repair offers Sydney',
  ' Auto glass repair offers Melbourne',
  ' Car window repair offers Sydney',
  ' Car window repair offers Melbourne',
  ' Windscreen repair offers Sydney',
  ' Windscreen repair offers Melbourne',
  ' Auto glass repair services Sydney',
  ' Auto glass repair services Melbourne',
  ' Car window repair services Sydney',
  ' Car window repair services Melbourne',
  ' Windscreen repair services Sydney',
  ' Windscreen repair services Melbourne',
  ' Auto glass repair solutions Sydney',
  ' Auto glass repair solutions Melbourne',
  ' Car window repair solutions Sydney',
  ' Car window repair solutions Melbourne',
  ' Windscreen repair solutions Sydney',
  ' Windscreen repair solutions Melbourne',
  ' Auto glass repair providers Sydney',
  ' Auto glass repair providers Melbourne',
  'Car window repair providers Sydney',
  'Car window repair providers Melbourne',
  'Windscreen repair providers Sydney',
  'Windscreen repair providers Melbourne',
  'Auto glass repair experts Sydney',
  'Auto glass repair experts Melbourne',
  'Car window repair experts Sydney',
  'Car window repair experts Melbourne',
  'Windscreen repair experts Sydney',
  'Windscreen repair experts Melbourne',
  'Auto glass repair',
  'How much does it cost to replace a car windshield in Sydney?',
  'How much does it cost to replace a car windshield in Melbourne?',
  'Are there 24/7 emergency auto glass repair services in Melbourne?',
  'Are there 24/7 emergency auto glass repair services in Sydney?',
  'Best auto glass repair services in Sydney',
  'Best auto glass repair services in Melbourne',
  'Mobile car window repair services in Sydney',
  'Mobile car window repair services in Melbourne'
]
